mysite/login_auth/urls.py
from django.conf.urls import url
from login_auth import views as login_views
from django.conf import settings

urlpatterns = [
               url(r'^login/$', login_views.login, name='login'),
               url(r'^logout/$', login_views.logout, name='logout'),
               url(r'^register/$', login_views.register, name='register')
               ]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('login_auth.urls'))
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

mysite/login_auth/models.py
from django.db import models

# Create your models here.

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

mysite/login_auth/views.py
from django.shortcuts import render, get_object_or_404  # render page, return data or 404 page
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm

def login(request):
    context = {}
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect('/polls')
        else:
            login_error = "User not exist"
            context = {"login_error": login_error}
            return render(request, 'login.html', context)
    else:
        return render(request, 'login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect("/auth/login")


def register(request):
    context = {} #?
    register_form = UserCreationForm()
    context = {"register_form": register_form}
    if request.method == "POST":
        new_user_form = UserCreationForm(request.POST)
        if new_user_form.is_valid():
            new_user_form.save()
            new_user = auth.authenticate(username=new_user_form.cleaned_data['username'],
                                         password=new_user_form.cleaned_data['password2'])
            auth.login(request, new_user)
            return HttpResponseRedirect('/polls')
        else:
            register_form = new_user_form
            context = {"register_form": register_form}
    return render(request, 'register.html', context)

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger #необходимо для переключения между страницами
from django.contrib import auth

from .models import Choice, Question



def index(request,):
    username = auth.get_user(request).username
    
    if request.user.is_authenticated():
        question_list = Question.objects.all()
        paginator = Paginator(question_list, 8) #Отображает 8 вопросов на странице
    
        page = request.GET.get('page')
        try:
            questions = paginator.page(page)
        except PageNotAnInteger:
            questions = paginator.page(1)
        except EmptyPage:
                questions = paginator.page(paginator.num_pages)
    
        return render_to_response('polls/index.html', {"questions": questions, "username": username})

    else :
        return HttpResponseRedirect("/auth/logout")



def detail(request, question_id):
    username = auth.get_user(request).username
    
    if request.user.is_authenticated():
        question = get_object_or_404(Question, pk=question_id)
        return render(request, 'polls/detail.html', {'question': question, 'username': username})

    else:
        return HttpResponseRedirect("/auth/logout")

def vote(request, question_id):
    username = auth.get_user(request).username
    
    if request.user.is_authenticated():
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
            #request.POST вызывает исключение KeyError, если такого ключа нет в наборе существующих
            #использую POST, а не GET, так как отправка формы изменяет данные.Иначе использовал бы GET
        except (KeyError, Choice.DoesNotExist):
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': "You didn't select a choice.",
            })
            #Обрабатывает KeyError и возвращает ошибку,если не выбран ни один вариант ответа
        else:
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
            #HttpResponseRedirect перенаправляет пользователя в результаты голосованя

    else:
        return HttpResponseRedirect("/auth/logout")


def results(request, question_id):
    username = auth.get_user(request).username
    
    if request.user.is_authenticated():
        question = get_object_or_404(Question, pk=question_id)
        return render(request, 'polls/results.html', {'question': question, 'username': username})

    else:
        return HttpResponseRedirect("/auth/logout")

mysite/login_auth/templates/login.html
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
            <style>
                li {
                    list-style-type: none; /* Убираем маркеры */
                }
            </style>
</head>

{% block login_auth %}
    <div class="login">
        <form action="/auth/login/" method="POST" align="center" style="font-size:20px">
            {% csrf_token %}
            <ul style="padding: 120px;">
            <label for="username">User name</label>
            <input type="text" name="username" id="username">
                <ul style="padding: 20px;">
                <label for="password" style="padding: 4px;">Password</label>
                <input type="password" name="password" id="password">
                    <ul style="padding: 20px;">
                    {% if login_error %}
                    <label class="error">{{ login_error }}</label>
                    {% endif %}
                    <input type="submit" value="Log in" class="btn btn-success">
                        </form>
        <ul style="padding: 25px;">
        <p class="register"><a  href="/auth/register/" class="btn btn-info">Not registered yet? Sign up</a></p>
    </div>
{% endblock login_auth %}

mysite/login_auth/templates/register.html
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
            <style>
                li {
                    list-style-type: none; /* Убираем маркеры */
                }
            </style>
</head>

{% load staticfiles %}

{% block login_auth %}
<div  class="wrapp_form">
    <ul style="padding-top: 120px;">
    <form action="/auth/register/" method="POST" align="center" style="font-size:20px">
        {% csrf_token %}
        {% for field in register_form %}
        <div class="form-group register_style">
            {{ field.errors }}
            {{ field.label_tag }}
            {{ field }}
        </div>
        {% endfor %}
        <input  type="submit" value="SIGN UP" class="btn btn-success" >
            </form>
</div>
{% endblock login_auth %}

mysite/polls/templates/polls/detail.html
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>

<h1 style="padding: 20px;">{{ question.question_text }}</h1>

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<ul style="padding-left: 30px;">
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
    <label for="choice{{ forloop.counter }}" style="padding: 5px;">{{ choice.choice_text }}</label><br />
{% endfor %}

<p style="padding-top: 30px;">
<input  type="submit" value="Vote" class="btn btn-primary"/>

</form>

mysite/polls/templates/polls/index.html
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
            <style>
                li {
                    list-style-type: none; /* Убираем маркеры */
                }
            </style>
</head>


<ul style="padding-top: 20px;">
<li class="auth_user"> <a href="/auth/logout/" class="btn btn-warning" >Log out ({{ username }})</a></li>
<ul style="padding: 20px;">



{% for question in questions %}
    <blockquote>
        <a href="/polls/{{ question.id }}/">{{ question.question_text }}</a>
    </blockquote>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if questions.has_previous %}
        <a href="?page={{ questions.previous_page_number }}"
            class="btn btn-primary"
            data-toggle="popover"
            title="Перейти к предыдущей странице"
            data-content=".">previous</a>
        {% endif %}
        
        <span class="current">
            <b style="padding: 10px;"> Page {{ questions.number }} of {{ questions.paginator.num_pages }} </b>
        </span>
        
        {% if questions.has_next %}
        <a href="?page={{ questions.next_page_number }}" class="btn btn-primary">next</a>
        {% endif %}
    </span>
</div>

mysite/polls/templates/polls/results.html
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>

<h1 style="padding: 20px;">{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<ul style="padding: 20px;">
<a href="/polls" class="btn btn-success">Back to all questions? </a>